### ISSUE TITLE
The names of the test should include spaces

### ISSUE THREAD

**Issue by baruza** [emender/documentation-conventions-tests#1]
Currently, the names of the tests do not include spaces:

DocumentationConventions
DocumentationGuidelines

Please add the spaces where appropriate:

Documentation Conventions
Documentation Guidelines

**Comment by baruza** [comment]
See also: https://github.com/emender/technical-accuracy-tests/issues/1

**Comment by tisnik** [comment]
It's been implemented in the Emender core in the following change sets:

* https://github.com/emender/emender/commit/6e9242dc9c0eb3338e26a4e61cb727dbe409ed73
* https://github.com/emender/emender/commit/b231f7a9f6deb4d2afcbd5794499d3e367920881
* https://github.com/emender/emender/commit/1e19d7ecd6e52c2d791e31c1f6bfacd7cb7f0ea6
